apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pjm3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-pjm3@sha256:5ded943d26687c1a277b79a67a97cbe1391c56f776b6ef1c65baa95e7c6e4ae8
        name: my-nodejs
        resources: {}
status: {}
